[phases.setup]
nixPkgs = [
    "python311",
    "gcc",
    "pkg-config", 
    "cairo.dev",
    "pango.dev",
    "gdk-pixbuf.dev",
    "libffi.dev",
    "freetype.dev",
    "fontconfig.dev",
    "libjpeg.dev",
    "libpng.dev",
    "zlib.dev",
    "gobject-introspection.dev"
]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && cd la_playita_project && gunicorn la_playita_project.wsgi:application --bind 0.0.0.0:$PORT"